### ISSUE TITLE
The key for sub collections appears to be different from the method generated by generateKeyFromId()

### ISSUE THREAD

**Issue by saurav050** [octabytes/FireO#100]
Below is the to_dict() of a sub collection orders. The parent collection is user.

**{'ctype': 'Direct', 'cstatus': 'Received', 'id': 'AuclsISMf9rHddH1yy48', 'key': 'user/mvG2acgfOnJiSwdEG95z/orders/AuclsISMf9rHddH1yy48'}**

Using the generateKeyFromId() method the key appears to be different than above
 ckey = utils.generateKeyFromId(Orders, id) 

Above line generates the below as key
**orders/AuclsISMf9rHddH1yy48**

I could be doing something wrong here, but wanted to raise this in case this is an issue.

**Comment by AxeemHaider** [comment]
`generateKeyFromId()` only concat **model name** and **id** check it [generateKeyFromId](https://github.com/octabytes/FireO/blob/master/src/fireo/utils/utils.py#L44)

if you want to generate full key you have to concat the `parent_key` with them. 

```python
key = parent_key + generateKeyFromId(Orders, id)
```
