### ISSUE TITLE
List of Nested Models

### ISSUE THREAD

**Issue by davidPalechor** [octabytes/FireO#103]
Hello FireO team!

I'm wondering if there is any support for list of Nested models. I'm looking forward to doing something like this.

```json
{
  "defaults": [
    {
      "attr1": "something1",
      "attr2": "something2"
    },
    {
      "attr1": "something3",
      "attr2": "something4"
    }
  ]
}
```

Using a different model for `attr1` and `attr2`

Is this possible?

Thanks!

**Comment by AxeemHaider** [comment]
There is related issue #96 

Might your requirements fulfil with [Map Field](https://octabyte.io/FireO/fields/map-field/)
if none of field fullfil your requirements then you create your [Custom Field](https://octabyte.io/FireO/fields/custom-field/)

**Comment by AxeemHaider** [comment]
Check this comment [FlexibleNestedModelField](https://github.com/octabytes/FireO/issues/101#issuecomment-820312418) by [monthero](https://github.com/monthero)

And see if it solve your problem
