### ISSUE TITLE
Can not filter document by customized document id field

### ISSUE THREAD

**Issue by xalien10** [octabytes/FireO#105]
I'm having the following model

```
class CompanyModel(Model):
    """
    Company Model for using with Repository
    """
    company_id = IDField(required=True)
    tenant_id = TextField(required=True)
    tenant_display_name = TextField(required=True)
    company_name = TextField(required=True)
    company_address = MapField()
    company_size = TextField()
    company_type = TextField()
```

But I can not filter CompanyModel using
`CompanyModel.collection.filter('company_id', '==', 'my-cid').get()`

Am I doing something wrong?

**Comment by AxeemHaider** [comment]
Document `ID` is special field and it is not saved in documents. 
Use it like this `CompanyModel.collection.get(document_key)` key contains **collection name** and **id**  If you have only id 
you can use the `utils` class to generate key from id and model.  

```python
doc_key = utils.generateKeyFromId(CompanyModel, "my-cid")
doc = CompanyModel.collection.get(doc_key)
```

If you still want to filter the document the save id also in document with `TextField`
something like this

```python
class User(Model):
    user_id = TextField() # instead of IDField. Now id saved in document
```

**Comment by xalien10** [comment]
Thank you for your quick and kind response. I think whether I didn't find
it in the documentation or I missed it some how.
