### ISSUE TITLE
Support for Meta model inheritance?

### ISSUE THREAD

**Issue by dhodun** [octabytes/FireO#106]
Hi Team,

Was hoping that the Meta: tags would get inherited but they seem not to be? It would be super helpful

Use cases:
- Creating a BaseModel(Model) class where ignore_none_field = False for ALL my objects
- Creating an object tree that is all stored in the same collection, hence my base NodeItem(Model) object has collection_name set and the individual nodes inherit from this.

**Comment by dhodun** [comment]
This appears to happen regardless whether the subclassed Model has a "Meta" class defined, so it's not a matter of it being overwritten.

**Comment by ADR-007** [comment]
Hi!
It is implemented in v1.8.0 (not released yet)
