### ISSUE TITLE
no support for nesting models inside list or map fields 

### ISSUE THREAD

**Issue by SaadAttieh** [octabytes/FireO#109]
support for the following types of models (pseudo code):
```
class User(Address):
    street = TextField()
    city = TextFielder()
    ...

class User(Model):
    name = TextField()
    addresses = ListField(Address())

```
or
```
    addresses = MapField(Address())
#key of map would of course be string, value would be address model.
```

**Comment by AxeemHaider** [comment]
Check this comment [FlexibleNestedModelField](https://github.com/octabytes/FireO/issues/101#issuecomment-820312418) by [monthero](https://github.com/monthero)

And see if it solve your problem

**Comment by R4Ajeti** [comment]
Hi @SaadAttieh ,

I tried this way and it worked for me, see if it is what you want:

```
class UserAddress(Model):
    street = TextField()
    city = TextField()
    ...

class User(Model):
    name = TextField()
    addresses = MapField(UserAddress())
```

**Comment by ADR-007** [comment]
I added support in [this](https://github.com/octabytes/FireO/pull/180) PR. It allows any number of levels of nested objects/lists

**Comment by ADR-007** [comment]
Hi @aelamran , you are right. I didn't implement it for MapField...
