### ISSUE TITLE
None values not being saved as null

### ISSUE THREAD

**Issue by JacksonMaxfield** [octabytes/FireO#115]
Hello!

I would love some clarification on if this is a bug or desired behavior.

If I have a model that looks like so:
```python
from fireo import fields
from fireo.models import Model

class Test(Model):
    name = fields.TextField(required=True)
    description = fields.TextField()
```

And I only set the :
```python
test_model = Test()

test_model.name = "hello world"
test_model.description = None

test_model.save()
```

The produced document only actually stores the `name` field.
![image](https://user-images.githubusercontent.com/17132317/126935998-9bc2b8b9-6a29-4548-be0f-64aa0d136169.png)

This is different from the Firebase admin API:
```python
from google.cloud.firestore_v1 import Client

db = Client.from_service_account_json(".keys/cdp-dev.json")
db.collection("test").add(
    {
        "name": "goodbye",
        "description": None,
    }
)
```

![image](https://user-images.githubusercontent.com/17132317/126936322-a57f6349-8f15-4b4e-9e71-42030f68403e.png)

In that the `None` value gets set to Firestore `null`.

Is this expected? Can I change this behavior? I would love to be able to store `None` -> `null`.

---

Also thank you for developing this library! It is really easy to use and adds a lot of functionality to the firebase ecosystem :slightly_smiling_face:

**Comment by AxeemHaider** [comment]
`None` fields are ignore by default but you can change this behaviour. Here is the [Documentation](https://octabyte.io/FireO/meta-class/#ignore-none-field-v135)
