### ISSUE TITLE
Batched writes does not update id,key for local objects

### ISSUE THREAD

**Issue by Deepak-Katchi** [octabytes/FireO#119]
Hi,

I want to write a large set of records to firestore and once I write them to firestore,  I do need the  ids of those records
For a single item, this can be done using 
`item.save();` 
`item.id` 
But since I have a large set of documents batched writes is the optimum way. But when I do it 
```
for item in items:
  item.save(batch)
batch.commit()

```
This writes items to firestore but when I do
`item[0].id`
it returns nothing

**Comment by Deepak-Katchi** [comment]
This happens with transactions too

**Comment by AxeemHaider** [comment]
Firestore does not return these ids because firestore handle these batch operations on their own side. 
This kind of thing is not support by firestore so FireO can't do it also
