### ISSUE TITLE
Provide a better documentation

### ISSUE THREAD

**Issue by guohaolee** [octabytes/FireO#12]
Hi ,

First of all, thank you creating a ORM library for Firebase! 

Appreciate if you can provide better documentation? Like how to inherit the Model class?

Like how do you import the TextField and etc. I mainly have to figure it out by diving into your tests and have a look how its implemented. It will be better if you can have a clearer documentation for at least the basic steps of creating an ORM. 

Cheers

**Comment by AxeemHaider** [comment]
Thanks for feedback. Actual documentation is available here https://octabyte.io/FireO/
But we will update our docs regarding what you are saying.
