### ISSUE TITLE
Run FireO test on GitHub actions

### ISSUE THREAD

**Issue by AxeemHaider** [octabytes/FireO#123]
Hi everyone!

FireO is running into an issue which I'm not able to solve. I was using Travis for testing and publishing python package.
But now travis-ci.org is not working anymore we have to shift on travis-ci.com but this is paid and some free features. So finally I decide to move on GitHub Actions. 

Issue I'm facing is when I try to run tests it require `GOOGLE_APPLICATION_CREDENTIALS` for firestore emulator don't know why it requiring this because everything is working fine on Travis. I had another repo [FireO NodeJs](https://github.com/octabytes/fireo-nodejs) where it is working fine without any additional **CREDENTIALS** 

I put an question on StackOverFlow but still not able to find the problem.
[Stackoverflow - Run Firestore emulator with Python in GitHub Actions](https://stackoverflow.com/questions/68569629/run-firestore-emulator-with-python-in-github-actions)

We have to solve this as soon as possible because without this we can't able to run **Tests**. 
Tests are failed due to `GOOGLE_APPLICATION_CREDENTIALS`

Can you please look into this issue

**Comment by isaacna** [comment]
I figured the issue out, will put out a PR for it shortly
