### ISSUE TITLE
1.4.5 release on PyPi

### ISSUE THREAD

**Issue by isaacna** [octabytes/FireO#125]
Could we get a 1.4.5 release on PyPi when possible? It contains the addition of `validator_kwargs` I added [here](https://github.com/octabytes/FireO/commit/b7705731c84a152c356eb88dc5b7941b71b6f454). We would like to use this in one of our projects that integrates FireO.

Thanks!

**Comment by AxeemHaider** [comment]
`version 1.4.5` is live https://pypi.org/project/fireo/
