### ISSUE TITLE
DO NOT FUCKING SPAM PEOPLE

### ISSUE THREAD

**Issue by lookfirst** [octabytes/FireO#13]
I just received an unsolicited email from you. I never signed up for your project or gave you my email address. You want my feedback? Ok. Don't fucking spam people.

Grrrrr....

![image](https://user-images.githubusercontent.com/85355/68183405-f6c59300-ffce-11e9-9c08-11bf324bb550.png)

**Comment by nelldnine** [comment]
I was also spammed but looking at the project, It's actually really cool.

**Comment by joemckie** [comment]
I got spammed too. Threw me off a bit as I’m helping work on [FireORM](https://github.com/wovalle/fireorm) which is a JS version of this

**Comment by AxeemHaider** [comment]
I'm really sorry. You got these emails if you not provided your email anywhere in our forums. 
This is separate team which handle these kind of campaign. 
This form is only meant to be for FireO development and issue related this. 
You can unsubscribe from this campaign. 

If you still have any issue you can directly contact with OctaByte team support@octabyte.io

**Comment by lookfirst** [comment]
@AxeemHaider You blame some other team? What?

**Comment by joemckie** [comment]
Sounds like data misuse 😅

**Comment by lookfirst** [comment]
@joemckie Exactly. Reporting it to Github now. Anyone else please do so as well. support@github.com

**Comment by joemckie** [comment]
I'm not sure exactly what GitHub could do. I'd personally report it to MailChimp which is where the email came from.

I did a bit of digging into the company, looks like they have some kind of Shopify app somewhere, so perhaps they grabbed our email through that?

**Comment by AxeemHaider** [comment]
Maybe they got it from Shopify app or somewhere else. Or maybe you subscribe the forum which is related to FireO like firestore or firebase. I'm here to handle development related to FireO and this forum is only for FireO issue. Don't misuse this GitHub issue. 

You can directly contact with OctaByte support support@github.com
