### ISSUE TITLE
Fireo models reference each other

### ISSUE THREAD

**Issue by R4Ajeti** [octabytes/FireO#130]
Hi,
How can i do this in fireo?

class Game(models.Model):
    # Other fields...
    on = models.ForeignKey('Member', blank = True)

class Member(models.Model):
    # Other fields...
    game = models.ForeignKey(Game)
    
  thank you

**Comment by AxeemHaider** [comment]
There is no field with the name of `ForeignKey` but [ReferenceField](https://octabyte.io/FireO/fields/reference-field/)
You can reference other documents using this field. But referencing each other document is bit difficult you can do it with out create the first document. How you can reference a document which is not exist. Might be it is possible if you already know the `id` of the document.
