### ISSUE TITLE
Can you create a document using a custom id

### ISSUE THREAD

**Issue by R4Ajeti** [octabytes/FireO#132]
Hi,
Was wondering if you can create a document using a custom id,
I use this: user = User.from_dict(dict_data) tryind to use also user._set_key('test') but didnt worked,
I tried also user.id = 'test' still didnt worked,
Then i tried also: u.save(merge=True) OR u.upsert() still no luck.
Looking forward for any help,

Happy coding :)

**Comment by AxeemHaider** [comment]
Yes this is possible. I recommend to read the Docs first before asking questions. 
Here you can find how to set custom id for document [https://octabyte.io/FireO/fields/id-field/](https://octabyte.io/FireO/fields/id-field/)

**Comment by AxeemHaider** [comment]
`from_dict()` return model object and you can make any changes into it.

```python
user = User.from_dict(dict_data)
user.id = "test"
```
