### ISSUE TITLE
Version 1.46.0 only supports google-cloud-firestore==2.1.0

### ISSUE THREAD

**Issue by TetianaHrunyk** [octabytes/FireO#133]
Background:
In the project I am working on we are trying to upgrade to Google Ads API v9, which is available in google-ads==14.1.0 package, which depends on google-api-core>=2.0.1,<3.0.0.
```
pipdeptree --packages google-ads
# First lines of the output
# google-ads==14.1.0
# - google-api-core [required: >=2.0.1,<3.0.0, installed: 1.31.4]
```
Meanwhile, the latest version of FireO has the following dependencies:
```
pipdeptree --packages fireo
# First lines of the output
# fireo==1.4.6
#  - google-cloud-firestore [required: ==2.1.0, installed: 2.1.0]
#    - google-api-core [required: >=1.22.1,<2.0.0dev, installed: 1.31.4]
```
I.e, these two packages have conflicting dependencies on the google-api-core package.

It would be nice to have support for google-cloud-firestore>=2.2.0, so that the users who combine firestore and google ads in their projects would be able to upgrade to the new version of google ads API.

**Comment by AxeemHaider** [comment]
Update `google-cloud-firestore` and run `FireO` tests if these are passed send a PR

**Comment by TetianaHrunyk** [comment]
Thank you for the response.

I have cloned the repo, changed the google-cloud-firestore version to the latest (currently 2.3.4), installed all the requirements, and run the tests. Some of the tests failed, so I have not created the PR. Below you can find a short summary of the test execution:
![image](https://user-images.githubusercontent.com/43062042/145393580-16956a7f-af70-4bee-b9e9-92f1f59032b8.png)

**Comment by AxeemHaider** [comment]
google cloud firestore version is updated to `2.2.0`
