### ISSUE TITLE
Consider changing license from GPL to LGPL

### ISSUE THREAD

**Issue by sethmlarson** [octabytes/FireO#14]
Many Python projects do this to ensure they can be used within non-Open Source projects while still having protections from being forked and redistributed by others for money. (See Paramiko, for example).

That said, the project looks great and I'd almost certainly end up using it given this change. It's something that's desperately needed by the Firebase team.

**Comment by AxeemHaider** [comment]
We are thinking to change the license to **Apache License 2.0** or **MIT** 
What you suggest ?

**Comment by sethmlarson** [comment]
I'd recommend Apache but the two are functionally the same as a liberal license. Thank you for your consideration!

**Comment by AxeemHaider** [comment]
License is changed now FireO is under [Apache License 2.0](https://github.com/octabytes/FireO/blob/master/LICENSE)
