### ISSUE TITLE
Quick start docs (https://octabyte.io/quick-start) does not exist

### ISSUE THREAD

**Issue by sohnryang** [octabytes/FireO#15]
I stumbled into this project because of ~~spam~~ some mail, and this project seems to be nice. However, when I looked at the docs, <https://octabyte.io/quick-start> gives 404.

Maybe you didn't wrote the quick start guide?

**Comment by AxeemHaider** [comment]
Where you got this link because this is not correct link. 
Documentation is available [here](https://octabyte.io/FireO/)
And Quickstart page is [here](https://octabyte.io/FireO/quick-start/)
