### ISSUE TITLE
How to get only document id's in a collection (or sub-collection) without opening all documents?

### ISSUE THREAD

**Issue by Dikilani** [octabytes/FireO#153]
Hello there,

I need this to save Firestore Read Count. Thank you in advance :)

All the best

**Comment by AxeemHaider** [comment]
I think this is not possible in Firestore you can't get only `ids` The only way is to query the collection and extract `id` from each document.

```python
docs = User.collection.fetch()
for d in docs:
   print(d.id)
```

**Other way**
Other way is save all documents id in separate documents which only contains the collection document ids and query this single document to get all the ids.
