### ISSUE TITLE
Validate FireO with google-cloud-firestore modules newer than 2.3.4

### ISSUE THREAD

**Issue by dhodun** [octabytes/FireO#174]
Currently FIreO is pinned to max of google-cloud-firestore 2.3.4 which is 16 months old.

Can we validate / increase the supported version?

https://github.com/octabytes/FireO/blob/9fc6fbb6dce44ee927dcc6228aa4cef4f30d5e88/setup.py#L72

https://pypi.org/project/google-cloud-firestore/#history

**Comment by AxeemHaider** [comment]
I think it was creating some problem try the Tests with latest version and see if there is any error?

**Comment by Ipceeh** [comment]
@AxeemHaider , I tried v1.8.0 tests with `google-cloud-firestore==2.10.0`. Result:
`=== 35 passed, 5 warnings in 43.99s ===`
Can we update dependency to 2.10.0 as it allows to use count aggregation query?

**Comment by AxeemHaider** [comment]
Updated use new version `2.0.0`
