### ISSUE TITLE
Internal field names being added to Model.field_list

### ISSUE THREAD

**Issue by cajones314** [octabytes/FireO#19]
On query the `Model.field_list` is being populated with the following internal fields:

`'parent', '_id', 'id', '_key', 'update_doc'`

My understanding is the `Model.field_list` should only include the fields in the document.

**Comment by AxeemHaider** [comment]
`Model.field_list` is keep each and every `field` for model class. As mention in the comments that `field_list` and `field_changed` and only used to track which field values are changed this is useful when updating the model. 

Logic for these `field_list` applied in [\_\_setattr\_\_](https://github.com/octabytes/FireO/blob/master/src/fireo/models/model.py#L374-L380)

I think `field_list` and `field_changed` should be **private** to avoid the confusion. 

### Important Note:
`field_list` are not the **document fields** if you want to get the document fields user `Model._meta.field_list` if you want to get name and value dict then you can use `Model._get_fields()` method

**Comment by cajones314** [comment]
@AxeemHaider if I use `Model._meta.field_list` then any fields that were "merged" do not show.

**Comment by AxeemHaider** [comment]
Yes it will not added to the `field_list` but you can easily added it by using this line `f.contribute_to_model(cls, f.name)` in `get_field_by_column_name` method

**Comment by cajones314** [comment]
@AxeemHaider some thought exercises:

1. how does a user determine what fields were merged when using FireO queries?
2. how does one determine the Field type (TextField, etc.) once a newly merge field has been detected?
3. how does one handle a merged field that is a nested type?

I suspect if you think about how those exercises are performed you will understand the challenges I am facing in using FireO as a Firestore ORM.

**Comment by AxeemHaider** [comment]
1 - Currently you can't determine which fields are merged. But merge field is added as `Base Field` and adding this line `f.contribute_to_model(cls, f.name)` will add the merge field in `_meta.field_list` 
We will add this in very next release (v040) which is coming in few days.

2 - It's easy to detect the field type `isinstance` can do this for you if you check the `model_meta.py` class you will get some examples how we are doing this.

3 - Nested types are merged as python dict type

**Comment by cajones314** [comment]
@AxeemHaider I suspect you will find that #2 is not as straightforward as you are stating.  Currently, when FireO creates a merged field it simply instantiates Field (base_field), and does not map the Firestore type to the appropriate Field Type.  Nested types will further compound the Type detection problem.  Lastly, your solution for #1 doesn't solve the thought experiment.  How does the user of FireO know what fields were merged when using the class instance--the simple answer is they can't easily--and won't be able too without using class introspection if you implement your proposed solution.

**Comment by AxeemHaider** [comment]
Yes exactly merged fields are simple instantiate as Base Field. 

Why we are not converting it into appropriate Field type because merge fields can not be used further for save or update operation. So there is no need to convert it into appropriate Field Type.

**Comment by cajones314** [comment]
@AxeemHaider are you saying forever and ever, that FireO will not allow the save, updating or deleting of a merged Field?  Seems a pretty drastic statement to make given it is only v1.

**Comment by AxeemHaider** [comment]
I'm saying currently it is not allowing but maybe in future. If we got further requests about this. 
Or you can contribute into it. 

Currently we are working in some other things if you notice FireO is not supported **batch operations** and **transactions** which are more important for us, Once we complete this then we thing about other functionalities.

**Comment by cajones314** [comment]
@AxeemHaider that is fair.  Once again, I personally don't make contributions to projects if the maintainers don't agree with the change.  It sounds like you aren't opposed to the change.  It would help make it very clear that when you do agree with the change that you open an issue as an approved feature request.  That way me or anyone else that wanted to work on it could do so knowing it wasn't wasted effort.

**Comment by AxeemHaider** [comment]
I already marked it as **enhancement** and added into project [features list](https://github.com/octabytes/FireO/projects/1?card_filter_query=label%3Aenhancement) You can send a pull request to us and it will be accepted.

**Comment by AxeemHaider** [comment]
Before you go further you need to pay attention on these things. These are very important for us and we have no plan to change it currently. 

There are one very important reserved word is `collection` which is a `manager` that is responsible to operate **Firestore** operations. For example `Model.collection.create()` we have no plan to change this word with any other e.g `getCollection()` or `collection()` I can also understand your condition that
some field with the same name `collection` can exist and this can create conflict But if you notice `collection` manager is only call from **Model** `class` it can't accessible from **Model** `instance` on the other side **fields** are access from **Model** `instance` not from **Model** `class` So some how you need to manage these two so we can use `collection` name as `manager`

For example:
**collection** name used as `manager`
`Model.collection.delete()`
**collection** name used as `field`
`model_instance.collection`

Second reserved name is `parent` **provide a better suggestion how we can manage this**

Third one is `id` you can change it like `getID()` but before this you need to look at this [IDField](https://octabyte.io/FireO/fields/id-field/) as mention in documentation user can change the name of `id` field **then how you manage it ?**
