### ISSUE TITLE
A way to use "id" instead of "key" in Manager

### ISSUE THREAD

**Issue by ADR-007** [octabytes/FireO#198]
I'm thinking about the right way to implement things like `Model.collection.get_by_id(<id>)`.

**Option 1:** Add `_by_id` suffix
Examples: 
```
Model.collection.get(<key>)
Model.collection.get_by_id(<id>)
```
**Option 2:** Add the "overloaded" versions of the methods:
Examples:
```
Model.collection.get(<key>)
Model.collection.get(<id>)
Model.collection.get(key=<key>)
Model.collection.get(id=<key>)
```
Implementation (fully supported by mypy):
```
    @overload
    def get(self, key, transaction=None):
        ...

    @overload
    def get(self, id, transaction=None):
        ...

    @convert_key_or_id_to_key
    def get(self, key, transaction=None):
        """Get document from firestore"""
        return self.queryset.get(key, transaction)
```

I think I prefer "option 2" but not sure yet. 🤔 

Affected methods in Manager:
<img width="527" alt="image" src="https://user-images.githubusercontent.com/7348960/225341559-abd0950f-9d05-4e40-a08b-a4e62d4b428c.png">

Any suggestions?

**Comment by AxeemHaider** [comment]
Hmmm... **Option 2** looks great.
