### ISSUE TITLE
Reserved field names...

### ISSUE THREAD

**Issue by cajones314** [octabytes/FireO#20]
In the Model implementation you list a number of names as being reserved (see https://octabyte.io/FireO/reserved-words/).

This is problematic for a number of reasons, such as the reserved names are not being checked when missing_field = merge setting causes errors on collisions.  I would like to propose an alternative naming/solution:  

If you want to keep the property access for the Model then change your reserved keywords to be of the form: `__.*__` as Firestore does not allow fields with those names.  This will prevent collisions.  For example, `_meta` would be `__.meta__`.

**Comment by AxeemHaider** [comment]
Currently There is no logic implement to check if user is using any reserved words on Model. 
Which mention in the documentation is only caution that don't use these **Reserved words** in model otherwise it will create conflict. 

These reserved word are not stored in Firestore some of these variables are for internal use and some provide more information about Model e.g `id` `collection_name` etc.

Your suggestion is good to change the name as `__.*__` but we can not convert all these reserved word to this because some of those used to show more information to user. 
For example `id` show the **id of the document** and `parent` provide key of the parent if there is any parent for this document. and `collection_name` tell in which collection this document is exist.
and `collection` is a manager that is responsible to operate Firestore operations.

So this is not possible to change the all these reserved word as you are suggest.

**Comment by cajones314** [comment]
@AxeemHaider if the concern is over recovering the id and collection_name then those should more than likely be methods: `getID()`, `getParent()`, `getCollection`.  

An ORM in general should not pollute the data model namespace with commonly used field names.  By having reserved field names outside the standard reserved names of Firestore that means users of your ORM must ensure their data models does not have fields that you have marked as reserved.  Given the names you have reserved that is a high barrier.  For example, id is used by most Firestore implementations, along with collection.  If your ORM is going to use class properties to assign fields, I strongly recommend you ensure your properties match 100% the Firestore document.  You can't achieve that because you are using reserved words in the standard namespace.    

I am personally trying to use FireO on 500mb of documents spread across a 50 collections.  Your choice of reserved words makes it unfortunately unusable.  :-(

**Comment by AxeemHaider** [comment]
You can still use the `id` word but this can be used only for `IDField` as mention in reserved words. 

But I also like your suggestion to create the method to access `id`, `collection_name` etc. 
We will try to do it any next release if possible because doing this we have backward compatibility issue.

For example as existing user of FireO is using the `Model.collection_name` or `Model.key` to access key and collection name if we change these into method as you suggest `getKey()` and `getCollection()` then after updating FireO his code will not work any more he need to change `Model.key` with `getKey()` every where.  What you suggest about this ?

Pull request are welcome checkout the feature branch and make changes according to your need and send us pull request we will merge it into FireO. Contributors are welcome!

**Comment by AxeemHaider** [comment]
I think you understand the **reserved words** wrong. These are not reserved for Firestore it only caution to not use it in **Model** otherwise you can use these names in Firestore. 

### For example: Valid
This is **valid** way and it can be use like this. In this example we are using three reserved word in firestore `id`, `field_list` and `parent` 
```python
class User(Model):
    doc_id = TextField(column_name='id')
    fields = ListField(column_name='field_list')
    parent_doc = TextField(column_name='parent')


u = User()
u.doc_id = 'Abc 123'
u.fields = ['f1', 'f2', 'f3']
u.parent_doc = 'parent_doc_id'
u.save()
```
It will save document in Firestore as

```
{
  'id': 'Abc 123', 
  'parent': 'parent_doc_id', 
  'field_list': ['f1', 'f2', 'f3']
}
````

### Example: Invalid
This is **not valid** way you can not use `reserved words` as class variable or instance variable. 
This will create conflict
```python
class User(Model):
    id = TextField()
    field_list = ListField()
    parent = TextField()
````

**Comment by cajones314** [comment]
@AxeemHaider I think the challenge here is how you expect FireO to be used.  If your project is used on brand-new project, then no issue with your restrictions.  However, if someone wants to retrofit their Firestore project using FireO then they will face the same challenges that I am.  Your example above perfectly highlights the challenges.

Take your document you created and try this:

```
  class Doc(Model):
    class Meta:
      collection_name = 'chris-playground'

  class ChildDoc(Model):
    class Meta:
      collection_name = 'child'

  docs = Doc.collection.fetch(1)
  doc = next(docs)

  print(f"id: {doc.id}")
  print(f"field_list: {doc.field_list}")
  print(f"parent: {doc.parent}")

  docs = ChildDoc.collection.parent(f"{doc._meta.collection_name}/{doc.id}").fetch(1)

  doc = next(docs)
  print(f"id: {doc.id}")
  print(f"field_list: {doc.field_list}")
  print(f"parent: {doc.parent}")
```
You will get the following output:
```
id: gKlDAmxxKLcmBAjzWLmM
field_list: ['f1', 'f2', 'f3', 'id', 'parent', '_id', '_key', 'update_doc']
parent: parent_doc_id
id: xsH40CukHnDinUcGDJIN
field_list: ['cf1', 'cf2', 'cf3', 'id', 'parent', '_id', '_key', 'update_doc']
parent: child_parent_doc_id
```

**Note:** the id has been overwritten with the document ID and the field_list has been polluted with the list from the document, and the parent has been changed to what is in the document.

This is the default result for FireO as the Meta default for `missing_field` is `merge`.   Of course, this is simplistic example as I didn't define the other fields, but clearly this is not how you expected FireO to work.  

Firestore is a NoSQL database, which means the exact issue I am pointing out is very likely for any existing Firestore projects.  These issues could have simply been avoided by naming your reserved properties with names that aren't allowed in Firestore (e.g. `__.*__`) or by changing your internal properties to have getters/setters.

**Comment by cajones314** [comment]
> But I also like your suggestion to create the method to access `id`, `collection_name` etc.
> We will try to do it any next release if possible because doing this we have backward compatibility issue.
> 
> For example as existing user of FireO is using the `Model.collection_name` or `Model.key` to access key and collection name if we change these into method as you suggest `getKey()` and `getCollection()` then after updating FireO his code will not work any more he need to change `Model.key` with `getKey()` every where. **_What you suggest about this ?_**

@AxeemHaider I understand that someone may have used FireO in a way that the changes I'm proposing would require them to change their code.  To me, that is not a showstopper.  It is very common for frameworks to introduce breaking changes.  The way that is handled is by using semantic versioning of the project: https://semver.org. Which states you change the MAJOR version number on breaking changes.  The existing user of FireO will be protected from the change because they should be using a package manager (like Pipfile) to specify what version of the code they are using.  Pipfile will not change the major version number that they initially used.  The developer would have to do that manually and it is their responsibility to read the changelog.md and be aware of any breaking changes.  For example, the Google Firestore API recently change getCollections() to listCollections().  That was a breaking change, but it was done for the right reasons, consistency in the API and clear communication of what the API call did through strong-naming.

**Comment by AxeemHaider** [comment]
First of all you don't need to create parent key manually 
`docs = ChildDoc.collection.parent(f"{doc._meta.collection_name}/{doc.id}").fetch(1)`
Just use like this
`docs = ChildDoc.collection.parent(doc.key).fetch(1)`
[Read Docs](https://octabyte.io/FireO/managing-data/adding-data/#sub-collection)

You are right if you use the `merge` functionality it will override the `id` and other fields and give a strange results. But this unusual to create a Model that is read only `merge` field only work when you read the fields from firestore you can't save any model without creating fields

**For example** 
 ```python
class Doc(Model):
    class Meta:
      collection_name = 'chris-playground'

d = Doc()
d.id = 'id123'
d.field_list = ['f1', 'f2']
d.name = 'Any Name'
d.save()  # it will not save any thing because these fields are not in model
```
Why you want this kind of Model which is **read only** ?

**Comment by cajones314** [comment]
> First of all you don't need to create parent key manually
> `docs = ChildDoc.collection.parent(f"{doc._meta.collection_name}/{doc.id}").fetch(1)`
> Just use like this
> `docs = ChildDoc.collection.parent(doc.key).fetch(1)`
> [Read Docs](https://octabyte.io/FireO/managing-data/adding-data/#sub-collection)

You are mistaken.  I can't use `doc.key` because `parent` was over written.  

```
print (doc.key)

parent_doc_id/chris-playground/gKlDAmxxKLcmBAjzWLmM
```

**Note:** the value of the parent field in the Firestore Doc has been prepended to the key.  I didn't point this out, because I thought it was self-evident since FireO allows a Firestore document to overwrite the reserverd field `parent`--back to my original point you should not name the reserved fields after valid Firestore doc field names.
 
> You are right if you use the `merge` functionality it will override the `id` and other fields and give a strange results. But this unusual to create a Model that is read only `merge` field only work when you read the fields from firestore you can't save any model without creating fields
> 

I believe you missed my statement, **_"Of course, this is simplistic example as I didn't define the other fields, but clearly this is not how you expected FireO to work."_**

> **For example**
> 
> ```python
> class Doc(Model):
>    class Meta:
>      collection_name = 'chris-playground'
> 
> d = Doc()
> d.id = 'id123'
> d.field_list = ['f1', 'f2']
> d.name = 'Any Name'
> d.save()  # it will not save any thing because these fields are not in model
> ```
> 
> Why you want this kind of Model which is **read only** ?

First, I don't won't a readonly Model.  I provided a simple example to highlight the issue with the FireO reserved field name choices.  Second, I pointed out that I believe merged fields should be writeable:  https://github.com/octabytes/FireO/issues/18

As for the overall why/what , I responded to you here: https://github.com/octabytes/FireO/issues/18#issuecomment-557317748

**Comment by AxeemHaider** [comment]
FireO merge functionality is never designed as you are expecting but This is a good suggestion to make merge fields writable. 

But as I comment in [other issue](https://github.com/octabytes/FireO/issues/19#issuecomment-557393048) we have some other work which has high priority
