### ISSUE TITLE
version 2.0.0 error with ListUnion/ListRemove

### ISSUE THREAD

**Issue by trungtin** [octabytes/FireO#202]
The released version 2.0.0 throw the error ListUnion object is not iterable. I saw that it had been fixed in the main branch. Could you release the new version?

**Comment by trungtin** [comment]
In fact, the issue is still there in the master branch.

If I define the schema like this, no error
```
class User(Model):
  subjects = ListField()  
  
u = User()
u.subjects = ['English', 'Math']
```

But with this (just like in the documentation), the error appears.
```
subjects = ListField(TextField())  
```

**Comment by trungtin** [comment]
Sorry, my stupid ass thought I was running on the master branch but not.

Anyway, do we have a new version release soon?

**Comment by ADR-007** [comment]
This is a question for @AxeemHaider :)

**Comment by AxeemHaider** [comment]
New version `2.1.0` is available with the help of @ADR-007 :)
