### ISSUE TITLE
ReferenceFields support for TypedModel

### ISSUE THREAD

**Issue by milanmitrovic** [octabytes/FireO#217]
I noticed that there is no reference field support for TypedModels. Is there a plan to add this functionality? Should I use some kind of workaround?

**Comment by ADR-007** [comment]
Hi! I don't work with Firestore anymore, and I am unsure if I will have time for this...
In general, you need to add a new `FieldResolver` to add support for the new type:

Something like this:
```py
class CustomAnnotationResolver(AnnotationResolver):
    resolvers = [*AnnotationResolver.resolvers, MyCustomTypeFieldResolver]

class MyModel(TypedModel):
   class Meta:
       annotation_resolver_cls = CustomAnnotationResolver

   my_field: MyCustomType
   ```

**Comment by milanmitrovic** [comment]
Thank you. I made it work along those lines.
