### ISSUE TITLE
Quering and filtering slowing down view render

### ISSUE THREAD

**Issue by ericel** [octabytes/FireO#33]
A query like the one below, drastically slows down my view render.

What would be the way to do such a query?
```
 @classmethod
    def get_updates(cls):
        questions = cls.collection.filter('status', '==', 'online').filter('type', '==', 'question').order('-updatedAt').fetch(4)
        products = cls.collection.filter('status', '==', 'online').filter('type', '==', 'market').order('-updatedAt').fetch(4)
        jobs = cls.collection.filter('status', '==', 'online').filter('type', '==', 'job').order('-updatedAt').fetch(4)
        blogs = cls.collection.filter('status', '==', 'online').filter('type', '==', 'blog').order('-updatedAt').fetch(4)
        pposts = cls.collection.filter('status', '==', 'online').order('-views').fetch(4)
        news = cls.collection.filter('status', '==', 'online').filter('type', '==', 'news').order('-updatedAt').fetch(4)
        return  questions, products, jobs, blogs, pposts, news
```
What would be the better way for such a view where it has to render content from different filters?

**Comment by AxeemHaider** [comment]
You can use `in` operator and check on App what is the type, is it question, products or jobs etc. 
In this way you can get you results in one single query.

**For example**

```python
updates = cls.collection.filter('type', 'in', ['question', 'market', 'job']).fetch()
```

Read More about [in and array-contains-any](https://octabyte.io/FireO/querying-data/querying-and-filtering/#in-and-array-contains-any)

**Comment by ericel** [comment]
Yes, but this won't really solve my problem. I want to get just 4 of each type. The about in operator, can't help with that? Or can it?

**Comment by AxeemHaider** [comment]
FireO help to use Firestore in easy way it's just a wrapper around Firestore. FireO itself does not provide any additional functionalities if it possible in Firestore you can do it also in FireO if not you can't do it also in FireO.
