### ISSUE TITLE
Is it possible to reference a field from another field?

### ISSUE THREAD

**Issue by jshep23** [octabytes/FireO#58]
Just want to say great work on this project! 

As for my question:
In other ORMs like NDB and Anom for datastore, you can create calculated fields. I'm migrating a sizable project from Datastore to Firestore, and I'm trying to implement the same functionality with FireO but can't figure it out.

I have something like this for the custom field:

```Python
class CalculatedField(Field):
  allowed_attributes = ['calc']
  
  def attr_calc(self, attr_val, field_val):
    if attr_val is not None:
      return attr_val()
    return None
```

Now in my model lets say I have something like this:

```Python
class Person(Model):
   name = TextField(required=True)
   name_lower = CalculatedField(calc=lamba self: self.name.lower())
```

And let's say I have a use case where I need to save the original formatted name, however the user entered it, but I also want to save the name in lower_case to make querying easier. I don't want to have to remember to always save the name twice, or if a new dev jumps on the project, he shouldn't have to just know that he or she needs to do that. But it doesn't seem like I can reference the model from the custom field in anyway or am I missing something?

I could do something like this:

```Python
class CalculatedField(Field):
  allowed_attributes = ['calc']
  
  def attr_calc(self, attr_val, field_val):
    if attr_val is not None:
      return attr_val(field_val)
    return None
```

```Python
class Person(Model):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.name_lower = self.name

   name = TextField(required=True)
   name_lower = CalculatedField(calc=lamba x: x.name.lower())
```

And this works when creating new objects of Person, but this doesn't work if the name changes.

Thanks again!

**Comment by AxeemHaider** [comment]
Currently FireO not support to reference other `fields` You can use simple coding to achieve it. 
For example you can use `method` to set name.

```python
def set_name(name):
    self.name = name
    self.name_lower = name
```

Everytime you call `set_name` both values are assign.

**Comment by jshep23** [comment]
Hey @AxeemHaider, thanks for the reply.

Yeah that's what I ended up doing for now. A CalculatedField would be a cool addition to FireO. Once I have some time, may fork this and see what I can do.

**Comment by jshep23** [comment]
Can close this Issue if you want, or mark it as feature request (not sure what you have for labels) and leave it here.
