### ISSUE TITLE
NestedModel fields throw exception when value is None

### ISSUE THREAD

**Issue by jshep23** [octabytes/FireO#61]
Model:
```python
class Car(Model):
  make = TextField()

class Person(Model):
  favorite_car = NestedModel(Car, required=False)  
```

If you try to create a Person object and set `favorite_car` to None:
```python
person = Person(favorite_car=None)
```
The following exception is thrown:

  File "/usr/local/lib/python3.8/site-packages/fireo/models/model.py", line 142, in __init__
    setattr(self, f.name, f.nested_model.from_dict(kwargs[f.name]))

  File "/usr/local/lib/python3.8/site-packages/fireo/models/model.py", line 149, in from_dict
    return cls(**model_dict)

TypeError: ModelMeta object argument after ** must be a mapping, not NoneType

The `required` attribute should check the field for None as well as the fields of type the NestedModel is based off of (which it already does). If required is True, and the NestedModel field is None, should through a more informative exception

**Comment by AxeemHaider** [comment]
This is solved in `version 1.3.0` But you have to understand `NestedModel` required field works a bit different. 

From [docs](https://octabyte.io/FireO/fields/nested-model/#required)

> This behave a little different in nested models. If you set `True` then it will check **required** fields inside nested model if there is any required field and no value is given then it will give error.
