### ISSUE TITLE
Dynamic collection name

### ISSUE THREAD

**Issue by zeretto** [octabytes/FireO#67]
Please I would like to know if is possible to create a collection name dynamically based on external parameter (IDs, etc.. )
For example a model "Event" that allow a parameter to make a collection_name = 'event_'+str(id)

Thanx

**Comment by AxeemHaider** [comment]
Yes, you can create `collection_name` dynamically. 

```python
class FireoDynamicCollection(Model):
    name = TextField()


o = FireoDynamicCollection()
FireoDynamicCollection.collection_name = "dynamic_collection_name"
o.name = "Azeem"
o.save()
```

There are also [Meta Class](https://octabyte.io/FireO/meta-class/#collection-name) which allow you to change collection 
name for your `Model`

**Comment by zeretto** [comment]
Perfect works great
