### ISSUE TITLE
Is it possible to save id as a field in a doc? 

### ISSUE THREAD

**Issue by brickgit** [octabytes/FireO#68]
I'm used to add a field `id` in docs so I can do `whereIn` query in collections. Is it possible to do that?

**Comment by skaaptjop** [comment]
I guess that depends on whether you want to generate the ID or whether you want Firestore to generate the ID.
If Firestore generates it for you then you won't know what it is until the document is created, then you'd have to update the document to set the ID field. Cumbersome but doable, can even be transaction wrapped I think.

**Comment by brickgit** [comment]
But the problem is we can't define a field named `id` as it's a reserved word, so I was wondering if there was a way to designate `id` to be saved in a doc?

**Comment by AxeemHaider** [comment]
I don't know why you need to save `id` in document. you can successfully operate all operation without doing this. But still if you want to do it you can. Firestore create `id` in `string` format.  

you can save like this. 

```python
class User(Model):
    id = TextField()
    name = TextField()

u = User()
u.id = "some-custom-id"
u.name = "My Name"
u.save()
```

You can get the document later like this. 

```python
from fireo.database import db

query = db.conn.collection("user").where("id", '==', "some-custom-id").get()

for doc in query:
    print(doc.to_dict())
```

**WARNING** But if you try to get `id` from `user` object it will not show you your **custom-id** but the firestore auto generated id. 

```python
print(u.id)
print(u.to_dict())
// In both way you will not see `some-custom-id` but firestore uid
```

if you want to save your `id` also in object you can do this.

```python
class User(Model):
    doc_id = TextField(required=True, column_name="id")
    name = TextField()


u = User()
u.doc_id = "some-custom-id"
u.name = "My Name"
u.save()

print(u.to_dict()) // Will give you your doc_id as well as firestore id
```

You can still perform same operation on this document. 

```pyhton
query = db.conn.collection("user").where("id", '==', "some-custom-id").get()
```
