### ISSUE TITLE
question about firebase collection map mapping

### ISSUE THREAD

**Issue by dzhdhr** [octabytes/FireO#69]
I was trying to insert data into a collection called UserData however when I set the collection name called UserData it keeps creating collection called user_data. Is there anyway to set the name correctly? Thanks.

**Comment by AxeemHaider** [comment]
You can use [Meta Class](https://octabyte.io/FireO/meta-class/#collection-name)

**Example Usage**

```python
class User(Model):
    name = TextField()

    class Meta:
        collection_name = "UserData"
```
