### ISSUE TITLE
No exception raised when indexes do not exist

### ISSUE THREAD

**Issue by TheSynt4x** [octabytes/FireO#75]
Hello!

I've encountered a problem with FireO that I've struggled with for some days. I finally wrapped my head around the issue. The issue was that I had forgotten to add exemptions in Firestore. This resulted in me getting an empty array when using `.group_fetch()` instead of an exception.

This piqued my interest and I took a closer look at the source code. In the `QueryIterator` class, whenever an exception is caught it just stops the iteration without raising any exceptions.

I believe the intention is to raise an exception, or am I wrong? Maybe it's intended? Please do let me know.

---

Edit: Some more information regarding this.

It seems that this isn't limited to only `group_fetch`, but to queries in general. 

### Using the `python-firestore` library
The following code **does** raise an exception:
```py
collection_group = db.collection_group(u'group_collection').where(u'example_id', u'==', '123')
results = collection_group.stream()

for result in results:
    print(result.id)
```

This is the exception that is raised:
```
google.api_core.exceptions.FailedPrecondition: 400 The query requires a COLLECTION_GROUP_ASC index for collection group_collection and field example_id. You can create it here: https://console.firebase.google.com/v1/r/project/project-here/firestore/indexes?create_exemption=exemption to create
``` 

### Using FireO
The following code **does not** raise an exception:
```py
from fireo import models, fields


class GroupCollection(models.Model):
  id = fields.IDField(required=True)
  example_id = fields.TextField(required=True, column_name='example_id')

  class Meta:
    collection_name = 'group_collection'

GroupCollection.collection.filter('example_id', '==', '123').group_fetch()
```

Both of these snippets are ran side-by-side in the same environment. While one succeeds at raising the exception (python-firestore), the other one does not (FireO). 

I believe that FireO does not raise the exception because of this:
```py
# fireo/queries/query_iterator.py, line 33-49

def __next__(self):
    try:
        doc = next(self.docs, None)
        if doc:
            # Suppose this is the last doc
            self.last_doc = doc
            m = query_wrapper.ModelWrapper.from_query_result(self.model_cls(), doc)
            m._update_doc = self.query._update_doc_key(m)
            # Suppose this is last doc
            self.last_doc_key = m.key
            return m
        self.fetch_end = True
        # Save last doc key in cursor
        self.query.cursor_dict['last_doc_key'] = self.last_doc_key
        raise StopIteration
    except Exception:
        raise StopIteration
```

The `except Exception` just stops the iteration. Is this intended?

**Comment by AxeemHaider** [comment]
Issue fixed in version `1.3.4` Update Fireo and you have good to go
