### ISSUE TITLE
Simultaneous connections to multiple databases

### ISSUE THREAD

**Issue by the-fool** [octabytes/FireO#76]
How can one have simultaneous connections with multiple credentials to multiple databases?  The documentation says this is possible: https://octabyte.io/FireO/authentication/#explicit-credentials

However, the `db` member is a global variable for the whole the module.  Presumably, I would need multiple instances of the `Database` class, each with different credentials.

**Comment by AxeemHaider** [comment]
Creating multiple instance of `Database` will not work for you I think you should have to pass **credentials** everytime when you need to change the database. 

For example:
```python
if(condition):
     fireo.connection(credentials=first_db_creds)
else:
     fireo.connection(credentials=second_db_creds)

# run your queries after this
User.collection.get();
```

**Comment by AxeemHaider** [comment]
Creating multiple instance of `Database` will not work for you I think you should have to pass **credentials** everytime when you need to change the database. 

For example:
```python
if(condition):
     fireo.connection(credentials=first_db_creds)
else:
     fireo.connection(credentials=second_db_creds)

# run your queries after this
User.collection.get();
```
