### ISSUE TITLE
Ability to "attach" to an existing collection specifying its name

### ISSUE THREAD

**Issue by tonjo** [octabytes/FireO#79]
As in title, I would like to create a model that reflects an already created collection.
I think it would be quite common, but I could be wrong.
Generally, it would be nice creating a model specifying a collection name.

**Comment by AxeemHaider** [comment]
You can create model and attach with your existing collections. You can name your model whatever you want. 
check [Meta Class -> collection name](https://octabyte.io/FireO/meta-class/#collection-name)

Also check [Missing fields](https://octabyte.io/FireO/meta-class/#missing-fields)
