### ISSUE TITLE
How to set TextField as unique?

### ISSUE THREAD

**Issue by inovizz** [octabytes/FireO#84]
Pardon my ignorance, I tried finding it in the document. Is it possible to do that?

**Comment by AxeemHaider** [comment]
What do you mean by setting `TextField` as **unique** ? Can you please explain it little bit more

**Comment by inovizz** [comment]
Nevermind, I got this working.

**Comment by R4Ajeti** [comment]
@inovizz How you go this working? can you pls share the solution?
 i need same thing here
