### ISSUE TITLE
Is it hard to implement set with merge=True option when saving a document?

### ISSUE THREAD

**Issue by tonjo** [octabytes/FireO#86]
Sorry if I put this as a question,
not a real issue.
I saw a precedent closed issue for upsert.
I know FireO `save()` is for creating, and `update()` is for updating, and currently there is no `upsert` available.
But with official firestore libraries is possible, by simply putting `merge=True` when saving.
Would it be too hard to simply add `merge` option to `save()` method, and on `set()` call inside `save()`?

I noticed `update` make a query first, so it's not atomic and not efficient, 2 operations instead of one.

(For me `update()` could even become useless, does not matter for me having an error if document is not present).

Again: thanks for the great job on this!

**Comment by AxeemHaider** [comment]
Under the `save()` it already use the `set()` method. [Create Query (save)](https://github.com/octabytes/FireO/blob/master/src/fireo/queries/create_query.py#L136)

You don't need to make a query first to `update()` document. Check out the [Update Documentation](https://octabyte.io/FireO/querying-data/updating-data/#using-key)

Check this issue also **Can I perform an upsert?** #37 

If still these are not fixing your problem then please provide little more detail what actually you are trying.

**Comment by tonjo** [comment]
Hi, excuse me if I was not perfectly clear.

0. Firestore has **natively** an upsert method: it's the `set()` method with `merge=True`.
1. I know `save()` uses `set()` method, but it does **not** implement `merge=True` option.  FireO's `save()` will completely overwrite a document if existant, removing existing fields. That option will prevent this, and update only speficied fields.
2. If I try to update a document that does not exist, FireO `update()` fails with an error, so I believe (maybe I'm wrong) Internally FireO method `update()` *performs a get first*. Not really needed with firestore, again, it could simply do a `set()` with that great  `merge=True` option. So FireO is inefficient when updating (no need to do a `get` first), and lacking a great functionality when creating (I can create or update with one function).
3. I saw issue #37, it says basically upsert is not implemented, you have to first get the document and than save it changing some fields, which is *not* an upsert, and that's why I asked if it's difficult to actually implement a cool, native, firestore functionality. Using `set()` with `merge=True` you can do 2 things: create a document if it does not exist, or update an existing one **without overwrite any other fields**. Again, you actually *can* do a real upsert with firestore's `set()`: just set `merge=True`.
Just look at [official firestore set() docs](https://firebase.google.com/docs/firestore/manage-data/add-data):
*If the document does not exist, it will be created. If the document does exist, its contents will be overwritten with the newly provided data, **unless you specify that the data should be merged into the existing document**, as follows:*

```city_ref = db.collection(u'cities').document(u'BJ')

city_ref.set({
    u'capital': True
}, merge=True)    # notice merge=True, completely missing in FireO
```
And below:
**If you're not sure whether the document exists, pass the option to merge the new data with any existing document to avoid overwriting entire documents.**

**Comment by AxeemHaider** [comment]
Update to newer version `v1.4.0`

**Comment by tonjo** [comment]
Wow, that was quick, amazing, thanks.
