### ISSUE TITLE
filter fail , result is  None

### ISSUE THREAD

**Issue by yxlwfds** [octabytes/FireO#93]
### data:
![image](https://user-images.githubusercontent.com/2525362/104832875-90751980-58cf-11eb-90f8-e8dc1ae5de13.png)
### code:
```
class Post(Model):
    id = IDField()
    category = ReferenceField(Category)
    lang = TextField(required=True)
    title = TextField(required=True)
    transtitle = MapField()
    content = TextField(required=True)
    tags = ListField()
    md5 = TextField()
    recommend = NumberField(default=0)
    active = BooleanField(default=False)
    created = DateTime(auto=True)

 p1 = Post.collection.filter(title='My First Post').get()
    
 print(p1)
```
### result is None
![image](https://user-images.githubusercontent.com/2525362/104832904-d7630f00-58cf-11eb-9b0e-d42e9d207113.png)

![image](https://user-images.githubusercontent.com/2525362/104832901-c9ad8980-58cf-11eb-8fa7-f4400baa8803.png)

**Comment by AxeemHaider** [comment]
It seems you are trying to search from **sub collection** if you want to search from **sub collection** you have to pass `parent key`   


Check example here [Querying and Filtering](https://octabyte.io/FireO/querying-data/querying-and-filtering/#sub-collection)
