### ISSUE TITLE
ListField of Models?

### ISSUE THREAD

**Issue by alejandroaas** [octabytes/FireO#96]
How can I save a ListField of previously defined models if I don't want to create a collection or a reference id for them?

**Comment by alejandroaas** [comment]
Maybe we should add ListField(NestedModel(X)), or ListField(X) to say is a list of objects from X model

**Comment by AxeemHaider** [comment]
`ListField` is actually `array` Here is the list of supported field from firestore [Supported data types](https://firebase.google.com/docs/firestore/manage-data/data-types)

There is [Map Field](https://octabyte.io/FireO/fields/map-field/) might you are looking this. if none of field fullfil your requirements then you create your [Custom Field](https://octabyte.io/FireO/fields/custom-field/)

**Comment by alejandroaas** [comment]
Yes, I agree. I would like the ListField (array) to be able to store and decode objects. That will be the little spice needed to do Nested Models but not one to one but one to many as well...

**Comment by AxeemHaider** [comment]
Any kind of Pull request will be acceptable.

For your knowledge firestore does not support `array` inside `array` but yes you can add `map` inside `array` 
Other thing I don't understand what do you mean by `custom field` return only **one element**? You can return anything which is acceptable by firestore all `FireO Fields` are extended from base `Field` class. Make sure to check `custom field` if it really did not full fill your requirements you can create the pull request

**Comment by alejandroaas** [comment]
I think I didn't explain myself well. Basically recursive saving with Models, you can achieve this with NestedModel(), but not for an array of NestedModel(). That is what I mean. So it would be interesting to store an array of nested models as maps the way you said it. For now, I am just going to use reference ids and use a list of ids.
