### ISSUE TITLE
Multitenancy support

### ISSUE THREAD

**Issue by anisrfd** [octabytes/FireO#98]
Isn't fireO support datastore mode? I need multitenancy support. So, if it is supported then please provide an example.

**Comment by AxeemHaider** [comment]
FireO use `google-cloud-firestore` under the hood which is specially design for `firestore` if `google-cloud-firestore` is not support **datastore mode** then the FireO will also not

**Comment by anisrfd** [comment]
Does fireO support multitenancy?
